routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index');
Route::resource('contacts', 'ContactController')->middleware('auth');

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    /**
     * Get the phone numbers for the contact.
     */
    public function phoneNumbers()
    {
        return $this->hasMany('App\PhoneNumber');
    }

    /**
     * Get the user who creates this contact.
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/PhoneNumber.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PhoneNumber extends Model
{
    /**
     * Get the contact this phone number belongs to.
     */
    public function contact()
    {
        return $this->belongsTo('App\Contact');
    }

    /**
     * Get the type of phone number.
     */
    public function type()
    {
        return $this->belongsTo('App\PhoneType', 'phone_type_id');
    }
}

app/PhoneType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PhoneType extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Get the contacts for the user.
     */
    public function contacts()
    {
        return $this->hasMany('App\Contact');
    }
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\PhoneType;
use App\PhoneNumber;
use App\Contact;
use App\User;
use App\Http\Requests\StoreContactRequest;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $my_contacts = $request->user()
            ->contacts()
            ->with('phoneNumbers.type')
            ->get()
            ->sortBy(function($contact) {
                return $contact->last_name;
            })
            ->values();

        return view('contacts.index', compact('my_contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $phone_types = PhoneType::all();

        return view('contacts.create', compact('phone_types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreContactRequest $request)
    {
        try {
            $contact = new Contact;
            $contact->last_name = $request->last_name;
            $contact->first_name = $request->first_name;
            $request->user()->contacts()->save($contact);

            for ($i = 0; $i < count($request->phone_number); $i++) {
                $new_phone_number = new PhoneNumber;
                $new_phone_number->phone_number = $request->phone_number[$i];
                $new_phone_number->phone_type_id = $request->phone_type[$i];
                $contact->phoneNumbers()->save($new_phone_number);
            }
        } catch (\Exception $e) {
            return redirect()->back()->with('error', "Sorry, some error occurred while trying to store the contact.");
        } 

        return redirect()->route('contacts.index')->with('message', "New contact ({$contact->first_name}) added.");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Contact $contact)
    {
        $this->authorize('edit', $contact);

        $phone_types = PhoneType::all();
        $primary_phone = $contact->phoneNumbers->shift();

        return view('contacts.edit', compact('contact', 'phone_types', 'primary_phone'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreContactRequest $request, Contact $contact)
    {
        $this->authorize('update', $contact);

        try {
            $contact->last_name = $request->last_name;
            $contact->first_name = $request->first_name;
            $contact->save();

            $contact->phoneNumbers()->delete();
            for ($i = 0; $i < count($request->phone_number); $i++) {
                $new_phone_number = new PhoneNumber;
                $new_phone_number->phone_number = $request->phone_number[$i];
                $new_phone_number->phone_type_id = $request->phone_type[$i];
                $contact->phoneNumbers()->save($new_phone_number);
            }
        } catch (\Exception $e) {
            return redirect()->back()->with('error', "Sorry, some error occurred while trying to update the contact.");
        } 

        return redirect()->route('contacts.edit', $contact->id)->with('message', "Contact ({$contact->first_name}) information saved.");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contact $contact)
    {
        $this->authorize('delete', $contact);

        try {
            $contact->phoneNumbers()->delete();
            $contact->delete();
        } catch (\Exception $e) {
            return redirect()->back()->with('error', "Sorry, some error occurred while trying to delete the contact.");
        }

        return redirect()->route('contacts.index')->with('message', "Contact ({$contact->first_name}) has been deleted.");;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/contacts/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Add New Contact</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('contacts.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="last_name" class="col-sm-4 col-form-label text-md-right">Last Name</label>

                            <div class="col-md-6">
                                <input id="last_name" class="form-control{{ $errors->has('last_name') ? ' is-invalid' : '' }}" name="last_name" value="{{ old('last_name') }}" placeholder="Doe" required autofocus>

                                @if ($errors->has('last_name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('last_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="first_name" class="col-sm-4 col-form-label text-md-right">First Name</label>

                            <div class="col-md-6">
                                <input id="first_name" class="form-control{{ $errors->has('first_name') ? ' is-invalid' : '' }}" name="first_name" value="{{ old('first_name') }}" placeholder="John" required>

                                @if ($errors->has('first_name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('first_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label text-md-right">Phone</label>

                            <div class="col-md-6">
                                <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        <select name="phone_type[]" class="form-control{{ $errors->has('phone_type') ? ' is-invalid' : '' }}" required>
                                            @foreach ($phone_types as $type)
                                                <option value="{{ $type->id }}">{{ $type->type }}</option>
                                            @endforeach
                                        </select>
                                    </div>

                                    <input class="form-control{{ $errors->has('phone_number.0') ? ' is-invalid' : '' }}" name="phone_number[]" placeholder="+6012-3456789" pattern="[\d\+-]{8,15}" required>

                                    @if ($errors->has('phone_number.0'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('phone_number.0') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                        </div>

                        <div id="phone-number-container">
                        </div>

                        <div class="form-group row">
                            <div class="col-md-6 offset-md-4">
                                <button class="btn btn-sm btn-outline-info" type="button" id="add-number-btn">
                                    <i class="fa fa-plus"></i>
                                </button>
                                <button class="btn btn-sm btn-outline-info" type="button" id="remove-number-btn">
                                    <i class="fa fa-minus"></i>
                                </button>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Save
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('custom_js')
<script id="template-add-number" type="text/template">
    <div class="form-group row">
        <div class="col-md-6 offset-md-4">
            <div class="input-group mb-2">
                <div class="input-group-prepend">
                    <select name="phone_type[]" class="form-control" required>
                        @foreach ($phone_types as $type)
                            <option value="{{ $type->id }}">{{ $type->type }}</option>
                        @endforeach
                    </select>
                </div>

                <input class="form-control" name="phone_number[]" placeholder="+6012-3456789"  pattern="[\d\+-]{8,15}" required>
            </div>
        </div>
    </div>
</script>

<script>
    $( document ).ready(function() {
        $('#add-number-btn').click( function() { 
            $('#phone-number-container').append( $('#template-add-number').html() );
        });

        $('#remove-number-btn').click( function() { 
            $('#phone-number-container').children().last().remove();
        });
    });
</script>
@endsection

resources/views/contacts/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Contact - {{ $contact->first_name }} {{ $contact->last_name }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('contacts.update', $contact->id) }}">
                        @method('PUT')
                        @csrf

                        <div class="form-group row">
                            <label for="last_name" class="col-sm-4 col-form-label text-md-right">Last Name</label>

                            <div class="col-md-6">
                                <input id="last_name" class="form-control{{ $errors->has('last_name') ? ' is-invalid' : '' }}" name="last_name" value="{{ old('last_name', $contact->last_name) }}" required>

                                @if ($errors->has('last_name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('last_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="first_name" class="col-sm-4 col-form-label text-md-right">First Name</label>

                            <div class="col-md-6">
                                <input id="first_name" class="form-control{{ $errors->has('first_name') ? ' is-invalid' : '' }}" name="first_name" value="{{ old('first_name', $contact->first_name) }}" required>

                                @if ($errors->has('first_name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('first_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label text-md-right">Phone</label>

                            <div class="col-md-6">
                                <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        <select name="phone_type[]" class="form-control{{ $errors->has('phone_type') ? ' is-invalid' : '' }}" required>
                                            @foreach ($phone_types as $type)
                                                <option value="{{ $type->id }}" {{ $primary_phone->type == $type ? "selected='selected'" : "" }}>{{ $type->type }}</option>
                                            @endforeach
                                        </select>
                                    </div>

                                    <input class="form-control" name="phone_number[]" value="{{ $primary_phone->phone_number }}" placeholder="+6012-3456789" pattern="[\d\+-]{8,15}" required>
                                </div>
                            </div>
                        </div>

                        <div id="phone-number-container">
                            @foreach ($contact->phoneNumbers as $number)
                                <div class="form-group row">
                                    <div class="col-md-6 offset-md-4">
                                        <div class="input-group mb-2">
                                            <div class="input-group-prepend">
                                                <select name="phone_type[]" class="form-control" required>
                                                    @foreach ($phone_types as $type)
                                                        <option value="{{ $type->id }}" {{ $number->type->id == $type->id ? "selected='selected'" : "" }}>{{ $type->type }}</option>
                                                    @endforeach
                                                </select>
                                            </div>

                                            <input class="form-control" name="phone_number[]" value="{{ $number->phone_number }}" placeholder="+6012-3456789"  pattern="[\d\+-]{8,15}" required>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>

                        <div class="col-md-6 offset-md-4">
                            @if ($errors->has('phone_number.0'))
                                <span class="invalid-feedback d-block" role="alert">
                                    <strong>{{ $errors->first('phone_number.0') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group row">
                            <div class="col-md-6 offset-md-4">
                                <button class="btn btn-sm btn-outline-info" type="button" id="add-number-btn">
                                    <i class="fa fa-plus"></i>
                                </button>
                                <button class="btn btn-sm btn-outline-info" type="button" id="remove-number-btn">
                                    <i class="fa fa-minus"></i>
                                </button>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Update
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('custom_js')
<script id="template-add-number" type="text/template">
    <div class="form-group row">
        <div class="col-md-6 offset-md-4">
            <div class="input-group mb-2">
                <div class="input-group-prepend">
                    <select name="phone_type[]" class="form-control" required>
                        @foreach ($phone_types as $type)
                            <option value="{{ $type->id }}">{{ $type->type }}</option>
                        @endforeach
                    </select>
                </div>

                <input class="form-control" name="phone_number[]" placeholder="+6012-3456789"  pattern="[\d\+-]{8,15}" required>
            </div>
        </div>
    </div>
</script>

<script>
    $( document ).ready(function() {
        $('#add-number-btn').click( function() { 
            $('#phone-number-container').append( $('#template-add-number').html() );
        });

        $('#remove-number-btn').click( function() { 
            $('#phone-number-container').children().last().remove();
        });
    });
</script>
@endsection

resources/views/contacts/index.blade.php
@extends('layouts.app')

@section('custom_css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.css" rel="stylesheet">
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1">
            <a class="btn btn-primary mb-4" href="{{ route('contacts.create') }}"><i class="fa fa-user-plus"></i> Add New Contact</a>

            <div class="card-columns">
                @forelse ($my_contacts as $contact)
                    <div class="card">
                        <div class="card-body">
                            <span class="card-title">{{ $contact->last_name }}, {{ $contact->first_name }}</span>
                            <form class="float-right ml-1" action="{{ route('contacts.destroy', $contact->id) }}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-sm btn-outline-danger delete-btn" type="submit">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </form>
                            <a class="btn btn-sm btn-outline-info float-right" href="{{ route('contacts.edit', $contact->id) }}">
                                <i class="fa fa-pencil"></i>
                            </a>
                            <div class="phone-numbers mt-3">
                            @foreach ($contact->phoneNumbers as $phone_number)
                                <span class="card-text">
                                    <i class="fa fa-phone"></i> {{ $phone_number->phone_number }} ({{ $phone_number->type->type }})<br />
                                </span>
                            @endforeach
                            </div>
                        </div>
                    </div>
                @empty
                    <p>You have not added any contact yet.</p>
                @endforelse
            </div>
        </div>
    </div>
</div>
@endsection

@section('custom_js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.js"></script>

<script>
$( document ).ready(function() {
    $(".delete-btn").click( function (e) {
        e.preventDefault();

        var form = event.target.form;
        var contactName = $(this).parent().siblings('.card-title').text();

        swal({
            title: "Are you sure to delete " + contactName + " from your Phonebook?",
            type: "error",
            confirmButtonClass: "btn-danger",
            confirmButtonText: "Yes",
            showCancelButton: true,
        }, function(confirmed) {
            if (confirmed) {
                form.submit();
            }
        });
    });
});
</script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Welcome to Phonebook App!</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    @auth
                        <a href="{{ route('contacts.index') }}" class="btn btn-outline-primary">
                            <i class="fa fa-address-book"> Open My Phonebook</i>
                        </a>
                    @endauth

                    @guest
                        Please login or register to continue
                    @endguest
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" 
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    @section('custom_css')
    @show
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('contacts.index') }}">My Contacts</a>
                        </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @if ($message = Session::get('error'))
                <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>	
                        <strong>{{ $message }}</strong>
                </div>
            @endif

            @if ($message = Session::get('message'))
                <div class="alert alert-info alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>	
                        <strong>{{ $message }}</strong>
                </div>
            @endif

            @yield('content')
        </main>
    </div>

    @section('custom_js')
    @show
</body>
</html>